USB IR HID Device: bootloader_firmware/usbdrv/usbdrv.c File Reference
bootloader_firmware/usbdrv/usbdrv.c File Reference
#include "iarcompat.h"
#include <avr/io.h>
#include <avr/pgmspace.h>
#include "usbdrv.h"
#include "oddebug.h"
Data Structures
union converter_t
Defines
#define IAR_SECTION(arg)
#define __no_init
#define USB_FLG_TX_PACKET (1<<0)
#define USB_FLG_MSGPTR_IS_ROM (1<<6)
#define USB_FLG_USE_DEFAULT_RW (1<<7)
#define PRG_RDB(addr) pgm_read_byte(addr)
Functions
__no_init uchar usbRxBuf[2][USB_BUFSIZE] __attribute__ ((section(USB_BUFFER_SECTION)))
void usbSetInterrupt (uchar *data, uchar len)
void usbPoll (void)
void usbInit (void)
Variables
uchar usbNakBuf [1] = {USBPID_NAK}
uchar * usbMsgPtr
Define Documentation
#define __no_init
Definition at line 27 of file usbdrv.c.
#define IAR_SECTION (arg)
Definition at line 26 of file usbdrv.c.
#define PRG_RDB (addr) pgm_read_byte(addr)
Definition at line 175 of file usbdrv.c.
#define USB_FLG_MSGPTR_IS_ROM (1<<6)
Definition at line 64 of file usbdrv.c.
#define USB_FLG_TX_PACKET (1<<0)
Definition at line 62 of file usbdrv.c.
#define USB_FLG_USE_DEFAULT_RW (1<<7)
Definition at line 65 of file usbdrv.c.
Function Documentation
__no_init uchar usbRxBuf [2][USB_BUFSIZE] __attribute__ ((section(USB_BUFFER_SECTION)))
Definition at line 37 of file usbdrv.c.
                                                                                                                                        : PID, 8 bytes data, 2 bytes CRC */
uchar       usbDeviceAddr;      /* assigned during enumeration, defaults to 0 */
uchar       usbNewDeviceAddr;   /* device ID which should be set after status phase */
uchar       usbConfiguration;   /* currently selected configuration. Administered by driver, but not used */
uchar       usbInputBuf;        /* ptr to raw buffer used for receiving */
uchar       usbAppBuf;          /* ptr to raw buffer passed to app for processing */
volatile schar usbRxLen;        /* = 0; number of bytes in usbAppBuf; 0 means free */
uchar       usbCurrentTok;      /* last token received */
uchar       usbRxToken;         /* token for data we received */
uchar       usbMsgLen = 0xff;   /* remaining number of bytes, no msg to send if -1 (see usbMsgPtr) */
volatile schar usbTxLen = -1;   /* number of bytes to transmit with next IN token */
uchar       usbTxBuf[USB_BUFSIZE];/* data to transmit with next IN, free if usbTxLen == -1 */
#if USB_CFG_HAVE_INTRIN_ENDPOINT
/* uchar       usbRxEndp;          endpoint which was addressed (1 bit in MSB) [not impl] */
volatile schar usbTxLen1 = -1;  /* TX count for endpoint 1 */
uchar       usbTxBuf1[USB_BUFSIZE];/* TX data for endpoint 1 */
#endif
uchar       usbAckBuf[1] = {USBPID_ACK};    /* transmit buffer for ack tokens */
void usbInit (void)
Definition at line 501 of file usbdrv.c.
Referenced by main().
{
    usbInputBuf = (uchar)usbRxBuf[0];
    usbAppBuf = (uchar)usbRxBuf[1];
#if USB_INTR_CFG_SET != 0
    USB_INTR_CFG |= USB_INTR_CFG_SET;
#endif
#if USB_INTR_CFG_CLR != 0
    USB_INTR_CFG &= ~(USB_INTR_CFG_CLR);
#endif
    USB_INTR_ENABLE |= (1 << USB_INTR_ENABLE_BIT);
}
void usbPoll (void)
Definition at line 452 of file usbdrv.c.
Referenced by main().
{
uchar   len;
    if((len = usbRxLen) > 0){
/* We could check CRC16 here -- but ACK has already been sent anyway. If you
 * need data integrity checks with this driver, check the CRC in your app
 * code and report errors back to the host. Since the ACK was already sent,
 * retries must be handled on application level.
 * unsigned crc = usbCrc16((uchar *)(unsigned)(usbAppBuf + 1), usbRxLen - 3);
 */
        len -= 3;       /* remove PID and CRC */
        if(len < 128){  /* no overflow */
            converter_t appBuf;
            appBuf.ptr = (uchar *)usbRxBuf;
            appBuf.bytes[0] = usbAppBuf;
            appBuf.bytes[0]++;
            usbProcessRx(appBuf.ptr, len);
        }
        usbRxLen = 0;   /* mark rx buffer as available */
    }
    if(usbMsgLen != 0xff){  /* transmit data pending? */
        if(usbTxLen < 0)    /* transmit system idle */
            usbBuildTxBlock();
    }
    if(isNotSE0()){ /* SE0 state */
        usbIsReset = 0;
    }else{
        /* check whether SE0 lasts for more than 2.5us (3.75 bit times) */
        if(!usbIsReset){
            uchar i;
            for(i=100;i;i--){
                if(isNotSE0())
                    goto notUsbReset;
            }
            usbIsReset = 1;
            usbNewDeviceAddr = 0;
            usbDeviceAddr = 0;
#if USB_CFG_IMPLEMENT_HALT
            usbHalted1 = 0;
#endif
            DBG1(0xff, 0, 0);
notUsbReset:;
        }
    }
}
void usbSetInterrupt (uchar * data, uchar len)
Definition at line 196 of file usbdrv.c.
Referenced by main().
{
uchar       *p, i;
#if USB_CFG_IMPLEMENT_HALT
    if(usbHalted1)
        return;
#endif
    if(len > 8) /* interrupt transfers are limited to 8 bytes */
        len = 8;
    i = USBPID_DATA1;
    if(usbTxPacketCnt1 & 1)
        i = USBPID_DATA0;
    if(usbTxLen1 < 0){      /* packet buffer was empty */
        usbTxPacketCnt1++;
    }else{
        usbTxLen1 = -1;     /* avoid sending incomplete interrupt data */
    }
    p = usbTxBuf1;
    *p++ = i;
    for(i=len;i--;)
        *p++ = *data++;
    usbCrc16Append(&usbTxBuf1[1], len);
    usbTxLen1 = len + 4;    /* len must be given including sync byte */
#if DEBUG_LEVEL > 1
    DBG2(0x21, usbTxBuf1, usbTxLen1-1);
#else
    DBG1(0x21, usbTxBuf1 + 1, 2);
#endif
}
Variable Documentation
uchar* usbMsgPtr
Definition at line 58 of file usbdrv.c.
Referenced by usbFunctionSetup().
uchar usbNakBuf[1] = {USBPID_NAK}
Definition at line 55 of file usbdrv.c.