USB IR HID Device: usbdrv/usbdrv.h File Reference
usbdrv/usbdrv.h File Reference
#include "usbconfig.h"
#include "iarcompat.h"
Data Structures
union usbWord
struct usbRequest
Defines
#define USBDRV_VERSION 20080418
#define uchar unsigned char
#define schar signed char
#define usbInterruptIsReady() (usbTxLen1 & 0x10)
#define usbHidReportDescriptor usbDescriptorHidReport
#define usbDeviceConnect()
#define usbDeviceDisconnect()
#define usbCrc16(data, len) usbCrc16((unsigned)(data), len)
#define usbCrc16Append(data, len) usbCrc16Append((unsigned)(data), len)
#define USB_STRING_DESCRIPTOR_HEADER(stringLength) ((2*(stringLength)+2) | (3<<8))
#define USB_SET_DATATOKEN1(token) usbTxBuf1[0] = token
#define USB_SET_DATATOKEN3(token) usbTxBuf3[0] = token
#define USB_PROP_IS_DYNAMIC (1 << 8)
#define USB_PROP_IS_RAM (1 << 9)
#define USB_PROP_LENGTH(len) ((len) & 0xff)
#define USB_CFG_DESCR_PROPS_HID_REPORT USB_CFG_HID_REPORT_DESCRIPTOR_LENGTH
#define USB_CONCAT(a, b) a ## b
#define USB_CONCAT_EXPANDED(a, b) USB_CONCAT(a, b)
#define USB_OUTPORT(name) USB_CONCAT(PORT, name)
#define USB_INPORT(name) USB_CONCAT(PIN, name)
#define USB_DDRPORT(name) USB_CONCAT(DDR, name)
#define USBOUT USB_OUTPORT(USB_CFG_IOPORTNAME)
#define USB_PULLUP_OUT USB_OUTPORT(USB_CFG_PULLUP_IOPORTNAME)
#define USBIN USB_INPORT(USB_CFG_IOPORTNAME)
#define USBDDR USB_DDRPORT(USB_CFG_IOPORTNAME)
#define USB_PULLUP_DDR USB_DDRPORT(USB_CFG_PULLUP_IOPORTNAME)
#define USBMINUS USB_CFG_DMINUS_BIT
#define USBPLUS USB_CFG_DPLUS_BIT
#define USBIDLE (1<<USB_CFG_DMINUS_BIT)
#define USBMASK ((1<<USB_CFG_DPLUS_BIT) | (1<<USB_CFG_DMINUS_BIT))
#define USB_CFG_IOPORT USB_OUTPORT(USB_CFG_IOPORTNAME)
#define USB_CFG_PULLUP_IOPORT USB_OUTPORT(USB_CFG_PULLUP_IOPORTNAME)
#define USB_BUFSIZE 11
#define USB_INTR_CFG MCUCR
#define USB_INTR_CFG_SET ((1 << ISC00) | (1 << ISC01))
#define USB_INTR_CFG_CLR 0
#define USB_INTR_ENABLE GICR
#define USB_INTR_ENABLE_BIT INT0
#define USB_INTR_PENDING GIFR
#define USB_INTR_PENDING_BIT INTF0
#define USBPID_SETUP 0x2d
#define USBPID_OUT 0xe1
#define USBPID_IN 0x69
#define USBPID_DATA0 0xc3
#define USBPID_DATA1 0x4b
#define USBPID_ACK 0xd2
#define USBPID_NAK 0x5a
#define USBPID_STALL 0x1e
#define USB_INITIAL_DATATOKEN USBPID_DATA1
#define USBRQ_RCPT_MASK 0x1f
#define USBRQ_RCPT_DEVICE 0
#define USBRQ_RCPT_INTERFACE 1
#define USBRQ_RCPT_ENDPOINT 2
#define USBRQ_TYPE_MASK 0x60
#define USBRQ_TYPE_STANDARD (0<<5)
#define USBRQ_TYPE_CLASS (1<<5)
#define USBRQ_TYPE_VENDOR (2<<5)
#define USBRQ_DIR_MASK 0x80
#define USBRQ_DIR_HOST_TO_DEVICE (0<<7)
#define USBRQ_DIR_DEVICE_TO_HOST (1<<7)
#define USBRQ_GET_STATUS 0
#define USBRQ_CLEAR_FEATURE 1
#define USBRQ_SET_FEATURE 3
#define USBRQ_SET_ADDRESS 5
#define USBRQ_GET_DESCRIPTOR 6
#define USBRQ_SET_DESCRIPTOR 7
#define USBRQ_GET_CONFIGURATION 8
#define USBRQ_SET_CONFIGURATION 9
#define USBRQ_GET_INTERFACE 10
#define USBRQ_SET_INTERFACE 11
#define USBRQ_SYNCH_FRAME 12
#define USBDESCR_DEVICE 1
#define USBDESCR_CONFIG 2
#define USBDESCR_STRING 3
#define USBDESCR_INTERFACE 4
#define USBDESCR_ENDPOINT 5
#define USBDESCR_HID 0x21
#define USBDESCR_HID_REPORT 0x22
#define USBDESCR_HID_PHYS 0x23
#define USBATTR_BUSPOWER 0x80
#define USBATTR_SELFPOWER 0x40
#define USBATTR_REMOTEWAKE 0x20
#define USBRQ_HID_GET_REPORT 0x01
#define USBRQ_HID_GET_IDLE 0x02
#define USBRQ_HID_GET_PROTOCOL 0x03
#define USBRQ_HID_SET_REPORT 0x09
#define USBRQ_HID_SET_IDLE 0x0a
#define USBRQ_HID_SET_PROTOCOL 0x0b
Typedefs
typedef union usbWord usbWord_t
typedef struct usbRequest usbRequest_t
Functions
USB_PUBLIC void usbInit (void)
USB_PUBLIC void usbPoll (void)
USB_PUBLIC uchar usbFunctionSetup (uchar data[8])
USB_PUBLIC uchar usbFunctionDescriptor (struct usbRequest *rq)
USB_PUBLIC void usbSetInterrupt (uchar *data, uchar len)
unsigned usbCrc16 (unsigned data, uchar len)
unsigned usbCrc16Append (unsigned data, uchar len)
Variables
uchar * usbMsgPtr
volatile uchar usbTxLen1
uchar usbConfiguration
PROGMEM char usbDescriptorDevice []
PROGMEM char usbDescriptorConfiguration []
PROGMEM char usbDescriptorHidReport []
PROGMEM char usbDescriptorString0 []
PROGMEM int usbDescriptorStringVendor []
PROGMEM int usbDescriptorStringDevice []
PROGMEM int usbDescriptorStringSerialNumber []
uchar usbTxBuf1 [USB_BUFSIZE]
uchar usbTxBuf3 [USB_BUFSIZE]
Define Documentation
#define schar signed char
Definition at line 149 of file usbdrv.h.
#define uchar unsigned char
Definition at line 146 of file usbdrv.h.
#define USB_BUFSIZE 11
Definition at line 538 of file usbdrv.h.
#define USB_CFG_DESCR_PROPS_HID_REPORT USB_CFG_HID_REPORT_DESCRIPTOR_LENGTH
Definition at line 414 of file usbdrv.h.
#define USB_CFG_IOPORT USB_OUTPORT(USB_CFG_IOPORTNAME)
Definition at line 529 of file usbdrv.h.
#define USB_CFG_PULLUP_IOPORT USB_OUTPORT(USB_CFG_PULLUP_IOPORTNAME)
Definition at line 531 of file usbdrv.h.
#define USB_CONCAT (a, b) a ## b
Definition at line 476 of file usbdrv.h.
#define USB_CONCAT_EXPANDED (a, b) USB_CONCAT(a, b)
Definition at line 477 of file usbdrv.h.
#define USB_DDRPORT (name) USB_CONCAT(DDR, name)
Definition at line 481 of file usbdrv.h.
#define USB_INITIAL_DATATOKEN USBPID_DATA1
Definition at line 608 of file usbdrv.h.
#define USB_INPORT (name) USB_CONCAT(PIN, name)
Definition at line 480 of file usbdrv.h.
#define USB_INTR_CFG MCUCR
Definition at line 546 of file usbdrv.h.
#define USB_INTR_CFG_CLR 0
Definition at line 553 of file usbdrv.h.
#define USB_INTR_CFG_SET ((1 << ISC00) | (1 << ISC01))
Definition at line 550 of file usbdrv.h.
#define USB_INTR_ENABLE GICR
Definition at line 562 of file usbdrv.h.
#define USB_INTR_ENABLE_BIT INT0
Definition at line 566 of file usbdrv.h.
#define USB_INTR_PENDING GIFR
Definition at line 573 of file usbdrv.h.
#define USB_INTR_PENDING_BIT INTF0
Definition at line 577 of file usbdrv.h.
#define USB_OUTPORT (name) USB_CONCAT(PORT, name)
Definition at line 479 of file usbdrv.h.
#define USB_PROP_IS_DYNAMIC (1 << 8)
Definition at line 372 of file usbdrv.h.
#define USB_PROP_IS_RAM (1 << 9)
Definition at line 376 of file usbdrv.h.
#define USB_PROP_LENGTH (len) ((len) & 0xff)
Definition at line 381 of file usbdrv.h.
#define USB_PULLUP_DDR USB_DDRPORT(USB_CFG_PULLUP_IOPORTNAME)
Definition at line 521 of file usbdrv.h.
#define USB_PULLUP_OUT USB_OUTPORT(USB_CFG_PULLUP_IOPORTNAME)
Definition at line 518 of file usbdrv.h.
#define USB_SET_DATATOKEN1 (token) usbTxBuf1[0] = token
Definition at line 354 of file usbdrv.h.
#define USB_SET_DATATOKEN3 (token) usbTxBuf3[0] = token
Definition at line 355 of file usbdrv.h.
#define USB_STRING_DESCRIPTOR_HEADER (stringLength) ((2*(stringLength)+2) | (3<<8))
Definition at line 332 of file usbdrv.h.
#define USBATTR_BUSPOWER 0x80
Definition at line 677 of file usbdrv.h.
#define USBATTR_REMOTEWAKE 0x20
Definition at line 679 of file usbdrv.h.
#define USBATTR_SELFPOWER 0x40
Definition at line 678 of file usbdrv.h.
#define usbCrc16 (data, len) usbCrc16((unsigned)(data), len)
Definition at line 295 of file usbdrv.h.
#define usbCrc16Append (data, len) usbCrc16Append((unsigned)(data), len)
Definition at line 303 of file usbdrv.h.
Referenced by usbSetInterrupt().
#define USBDDR USB_DDRPORT(USB_CFG_IOPORTNAME)
Definition at line 520 of file usbdrv.h.
#define USBDESCR_CONFIG 2
Definition at line 669 of file usbdrv.h.
#define USBDESCR_DEVICE 1
Definition at line 668 of file usbdrv.h.
#define USBDESCR_ENDPOINT 5
Definition at line 672 of file usbdrv.h.
#define USBDESCR_HID 0x21
Definition at line 673 of file usbdrv.h.
#define USBDESCR_HID_PHYS 0x23
Definition at line 675 of file usbdrv.h.
#define USBDESCR_HID_REPORT 0x22
Definition at line 674 of file usbdrv.h.
#define USBDESCR_INTERFACE 4
Definition at line 671 of file usbdrv.h.
#define USBDESCR_STRING 3
Definition at line 670 of file usbdrv.h.
#define usbDeviceConnect ()
Value:
((USB_PULLUP_DDR |= (1<<USB_CFG_PULLUP_BIT)), \
                                  (USB_PULLUP_OUT |= (1<<USB_CFG_PULLUP_BIT)))
Definition at line 274 of file usbdrv.h.
Referenced by main().
#define usbDeviceDisconnect ()
Value:
((USB_PULLUP_DDR &= ~(1<<USB_CFG_PULLUP_BIT)), \
                                  (USB_PULLUP_OUT &= ~(1<<USB_CFG_PULLUP_BIT)))
Definition at line 276 of file usbdrv.h.
Referenced by main().
#define USBDRV_VERSION 20080418
Definition at line 125 of file usbdrv.h.
#define usbHidReportDescriptor usbDescriptorHidReport
Definition at line 226 of file usbdrv.h.
#define USBIDLE (1<<USB_CFG_DMINUS_BIT)
Definition at line 525 of file usbdrv.h.
#define USBIN USB_INPORT(USB_CFG_IOPORTNAME)
Definition at line 519 of file usbdrv.h.
#define usbInterruptIsReady () (usbTxLen1 & 0x10)
Definition at line 213 of file usbdrv.h.
#define USBMASK ((1<<USB_CFG_DPLUS_BIT) | (1<<USB_CFG_DMINUS_BIT))
Definition at line 526 of file usbdrv.h.
#define USBMINUS USB_CFG_DMINUS_BIT
Definition at line 523 of file usbdrv.h.
#define USBOUT USB_OUTPORT(USB_CFG_IOPORTNAME)
Definition at line 517 of file usbdrv.h.
#define USBPID_ACK 0xd2
Definition at line 603 of file usbdrv.h.
#define USBPID_DATA0 0xc3
Definition at line 600 of file usbdrv.h.
#define USBPID_DATA1 0x4b
Definition at line 601 of file usbdrv.h.
#define USBPID_IN 0x69
Definition at line 599 of file usbdrv.h.
#define USBPID_NAK 0x5a
Definition at line 604 of file usbdrv.h.
#define USBPID_OUT 0xe1
Definition at line 598 of file usbdrv.h.
#define USBPID_SETUP 0x2d
Definition at line 597 of file usbdrv.h.
#define USBPID_STALL 0x1e
Definition at line 605 of file usbdrv.h.
#define USBPLUS USB_CFG_DPLUS_BIT
Definition at line 524 of file usbdrv.h.
#define USBRQ_CLEAR_FEATURE 1
Definition at line 656 of file usbdrv.h.
#define USBRQ_DIR_DEVICE_TO_HOST (1<<7)
Definition at line 652 of file usbdrv.h.
#define USBRQ_DIR_HOST_TO_DEVICE (0<<7)
Definition at line 651 of file usbdrv.h.
#define USBRQ_DIR_MASK 0x80
Definition at line 650 of file usbdrv.h.
#define USBRQ_GET_CONFIGURATION 8
Definition at line 661 of file usbdrv.h.
#define USBRQ_GET_DESCRIPTOR 6
Definition at line 659 of file usbdrv.h.
#define USBRQ_GET_INTERFACE 10
Definition at line 663 of file usbdrv.h.
#define USBRQ_GET_STATUS 0
Definition at line 655 of file usbdrv.h.
#define USBRQ_HID_GET_IDLE 0x02
Definition at line 683 of file usbdrv.h.
#define USBRQ_HID_GET_PROTOCOL 0x03
Definition at line 684 of file usbdrv.h.
#define USBRQ_HID_GET_REPORT 0x01
Definition at line 682 of file usbdrv.h.
#define USBRQ_HID_SET_IDLE 0x0a
Definition at line 686 of file usbdrv.h.
#define USBRQ_HID_SET_PROTOCOL 0x0b
Definition at line 687 of file usbdrv.h.
#define USBRQ_HID_SET_REPORT 0x09
Definition at line 685 of file usbdrv.h.
#define USBRQ_RCPT_DEVICE 0
Definition at line 639 of file usbdrv.h.
#define USBRQ_RCPT_ENDPOINT 2
Definition at line 641 of file usbdrv.h.
#define USBRQ_RCPT_INTERFACE 1
Definition at line 640 of file usbdrv.h.
#define USBRQ_RCPT_MASK 0x1f
Definition at line 638 of file usbdrv.h.
#define USBRQ_SET_ADDRESS 5
Definition at line 658 of file usbdrv.h.
#define USBRQ_SET_CONFIGURATION 9
Definition at line 662 of file usbdrv.h.
#define USBRQ_SET_DESCRIPTOR 7
Definition at line 660 of file usbdrv.h.
#define USBRQ_SET_FEATURE 3
Definition at line 657 of file usbdrv.h.
#define USBRQ_SET_INTERFACE 11
Definition at line 664 of file usbdrv.h.
#define USBRQ_SYNCH_FRAME 12
Definition at line 665 of file usbdrv.h.
#define USBRQ_TYPE_CLASS (1<<5)
Definition at line 646 of file usbdrv.h.
#define USBRQ_TYPE_MASK 0x60
Definition at line 644 of file usbdrv.h.
#define USBRQ_TYPE_STANDARD (0<<5)
Definition at line 645 of file usbdrv.h.
#define USBRQ_TYPE_VENDOR (2<<5)
Definition at line 647 of file usbdrv.h.
Typedef Documentation
typedef struct usbRequest usbRequest_t
typedef union usbWord usbWord_t
Function Documentation
unsigned usbCrc16 (unsigned data, uchar len)
unsigned usbCrc16Append (unsigned data, uchar len)
USB_PUBLIC uchar usbFunctionDescriptor (struct usbRequest * rq)
USB_PUBLIC uchar usbFunctionSetup (uchar data[8])
Definition at line 55 of file main.c.
{
    uchar len = 0;
    if (data[1] == USBBOOT_FUNC_LEAVE_BOOT) {
      leaveBootloader();
    } else if (data[1] == USBBOOT_FUNC_WRITE_PAGE) {
      state = STATE_WRITE_PAGE;
      page_address = (data[3] << 8) | data[2]; /* page address */
      page_offset = 0;
      eeprom_busy_wait();
      cli();
      boot_page_erase(page_address); /* erase page */
      sei();
      boot_spm_busy_wait(); /* wait until page is erased */
      len = 0xff; /* multiple out */
    } else if (data[1] == USBBOOT_FUNC_GET_PAGESIZE) {
      replyBuffer[0] = SPM_PAGESIZE >> 8;
      replyBuffer[1] = SPM_PAGESIZE & 0xff;
      len = 2;
    }
    usbMsgPtr = replyBuffer;
    return len;
}
USB_PUBLIC void usbInit (void)
Definition at line 501 of file usbdrv.c.
Referenced by main().
{
    usbInputBuf = (uchar)usbRxBuf[0];
    usbAppBuf = (uchar)usbRxBuf[1];
#if USB_INTR_CFG_SET != 0
    USB_INTR_CFG |= USB_INTR_CFG_SET;
#endif
#if USB_INTR_CFG_CLR != 0
    USB_INTR_CFG &= ~(USB_INTR_CFG_CLR);
#endif
    USB_INTR_ENABLE |= (1 << USB_INTR_ENABLE_BIT);
}
USB_PUBLIC void usbPoll (void)
Definition at line 452 of file usbdrv.c.
Referenced by main().
{
uchar   len;
    if((len = usbRxLen) > 0){
/* We could check CRC16 here -- but ACK has already been sent anyway. If you
 * need data integrity checks with this driver, check the CRC in your app
 * code and report errors back to the host. Since the ACK was already sent,
 * retries must be handled on application level.
 * unsigned crc = usbCrc16((uchar *)(unsigned)(usbAppBuf + 1), usbRxLen - 3);
 */
        len -= 3;       /* remove PID and CRC */
        if(len < 128){  /* no overflow */
            converter_t appBuf;
            appBuf.ptr = (uchar *)usbRxBuf;
            appBuf.bytes[0] = usbAppBuf;
            appBuf.bytes[0]++;
            usbProcessRx(appBuf.ptr, len);
        }
        usbRxLen = 0;   /* mark rx buffer as available */
    }
    if(usbMsgLen != 0xff){  /* transmit data pending? */
        if(usbTxLen < 0)    /* transmit system idle */
            usbBuildTxBlock();
    }
    if(isNotSE0()){ /* SE0 state */
        usbIsReset = 0;
    }else{
        /* check whether SE0 lasts for more than 2.5us (3.75 bit times) */
        if(!usbIsReset){
            uchar i;
            for(i=100;i;i--){
                if(isNotSE0())
                    goto notUsbReset;
            }
            usbIsReset = 1;
            usbNewDeviceAddr = 0;
            usbDeviceAddr = 0;
#if USB_CFG_IMPLEMENT_HALT
            usbHalted1 = 0;
#endif
            DBG1(0xff, 0, 0);
notUsbReset:;
        }
    }
}
USB_PUBLIC void usbSetInterrupt (uchar * data, uchar len)
Definition at line 196 of file usbdrv.c.
Referenced by main().
{
uchar       *p, i;
#if USB_CFG_IMPLEMENT_HALT
    if(usbHalted1)
        return;
#endif
    if(len > 8) /* interrupt transfers are limited to 8 bytes */
        len = 8;
    i = USBPID_DATA1;
    if(usbTxPacketCnt1 & 1)
        i = USBPID_DATA0;
    if(usbTxLen1 < 0){      /* packet buffer was empty */
        usbTxPacketCnt1++;
    }else{
        usbTxLen1 = -1;     /* avoid sending incomplete interrupt data */
    }
    p = usbTxBuf1;
    *p++ = i;
    for(i=len;i--;)
        *p++ = *data++;
    usbCrc16Append(&usbTxBuf1[1], len);
    usbTxLen1 = len + 4;    /* len must be given including sync byte */
#if DEBUG_LEVEL > 1
    DBG2(0x21, usbTxBuf1, usbTxLen1-1);
#else
    DBG1(0x21, usbTxBuf1 + 1, 2);
#endif
}
Variable Documentation
uchar usbConfiguration
Definition at line 32 of file usbdrv.c.
PROGMEM char usbDescriptorConfiguration[]
Definition at line 143 of file usbdrv.c.
PROGMEM char usbDescriptorDevice[]
Definition at line 114 of file usbdrv.c.
PROGMEM char usbDescriptorHidReport[]
PROGMEM char usbDescriptorString0[]
Definition at line 75 of file usbdrv.c.
PROGMEM int usbDescriptorStringDevice[]
Definition at line 94 of file usbdrv.c.
PROGMEM int usbDescriptorStringSerialNumber[]
PROGMEM int usbDescriptorStringVendor[]
Definition at line 85 of file usbdrv.c.
uchar* usbMsgPtr
Definition at line 58 of file usbdrv.c.
Referenced by usbFunctionSetup().
uchar usbTxBuf1[USB_BUFSIZE]
Definition at line 44 of file usbdrv.c.
Referenced by usbSetInterrupt().
uchar usbTxBuf3[USB_BUFSIZE]
volatile uchar usbTxLen1
Definition at line 43 of file usbdrv.c.